import { env } from "@/env";
import type { PlansData } from "@/types";

export const plans: PlansData = {
  oneTime: [
    {
      id: "ot_basic",
      priceId: env.STRIPE_PRICE_ID_OT_BASIC,
      title: "Basic Report",
      description: "A single detailed report.",
      price: "$49",
      features: ["One-time analysis", "Standard metrics", "Email support"],
      cta: "Purchase Now",
    },
    {
      id: "ot_pro",
      priceId: env.STRIPE_PRICE_ID_OT_PRO,
      title: "Pro Report Pack",
      description: "Pack of 5 detailed reports.",
      price: "$199",
      features: [
        "Five reports bundle",
        "Advanced metrics",
        "Priority email support",
      ],
      cta: "Purchase Pack",
    },
  ],
  monthly: [
    {
      id: "mo_starter",
      priceId: env.STRIPE_PRICE_ID_MO_STARTER,
      title: "Starter Monthly",
      description: "Ideal for individuals getting started.",
      price: "$29",
      period: "/month",
      features: [
        "Up to 10 reports/mo",
        "Basic analytics",
        "Community support",
        "Cancel anytime",
      ],
      cta: "Choose Starter",
    },
    {
      id: "mo_business",
      priceId: env.STRIPE_PRICE_ID_MO_BUSINESS,
      title: "Business Monthly",
      description: "Perfect for small teams & businesses.",
      price: "$79",
      period: "/month",
      features: [
        "Up to 50 reports/mo",
        "Advanced analytics",
        "Priority support",
        "Team features",
        "Cancel anytime",
      ],
      cta: "Choose Business",
      popular: true,
    },
    {
      id: "mo_enterprise",
      priceId: env.STRIPE_PRICE_ID_MO_ENTERPRISE,
      title: "Enterprise Monthly",
      description: "For large organizations.",
      price: "$249",
      period: "/month",
      features: [
        "Unlimited reports",
        "Custom analytics",
        "Dedicated support",
        "API Access",
        "Cancel anytime",
      ],
      cta: "Contact Sales",
    },
  ],
  annual: [
    {
      id: "yr_starter",
      priceId: env.STRIPE_PRICE_ID_YR_STARTER,
      title: "Starter Annual",
      description: "Get 2 months free!",
      price: "$290",
      period: "/year",
      features: [
        "Up to 10 reports/mo",
        "Basic analytics",
        "Community support",
        "Billed annually",
      ],
      cta: "Choose Starter Annual",
    },
    {
      id: "yr_business",
      priceId: env.STRIPE_PRICE_ID_YR_BUSINESS,
      title: "Business Annual",
      description: "Most popular, with savings!",
      price: "$790",
      period: "/year",
      features: [
        "Up to 50 reports/mo",
        "Advanced analytics",
        "Priority support",
        "Team features",
        "Billed annually",
      ],
      cta: "Choose Business Annual",
      popular: true,
    },
    {
      id: "yr_enterprise",
      priceId: env.STRIPE_PRICE_ID_YR_ENTERPRISE,
      title: "Enterprise Annual",
      description: "Best value for large teams.",
      price: "$2490",
      period: "/year",
      features: [
        "Unlimited reports",
        "Custom analytics",
        "Dedicated support",
        "API Access",
        "Billed annually",
      ],
      cta: "Contact Sales",
    },
  ],
};
